name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - name: Composer
      uses: php-actions/composer@v6
    - name: PhpStan
      uses: php-actions/phpstan@v3
      with:
        path: app/ config/ database/ tests/
        configuration: phpstan.neon
    - name: ECS
      uses: pietrzakadrian/easy-coding-standard-github-action@v2.0.3
      with:
        config: ecs.php
        directories: app/ config/ routes/ tests/
